project-includes = ["src"]
project-excludes = ["**/tests"]
search-path = ["src"]
site-package-path = [".venv/Lib/site-packages"]

python-platform = "windows"
python-version = "3.12"
python-interpreter-path = ".venv/Scripts/python"